defaultBackend:
  nodeSelector:
    beta.kubernetes.io/os: linux
controller:
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  replicaCount: 2
  nodeSelector:
    beta.kubernetes.io/os: linux
  extraVolumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-tls"
          #nodePublishSecretRef:
          #  name: secrets-store-creds
  extraVolumeMounts:
      - name: secrets-store-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true